/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShadedReliefRouteImport } from './routes/shaded-relief'
import { Route as RmaVisitorPostgisRouteImport } from './routes/rma-visitor-postgis'
import { Route as RmaAndroidRouteImport } from './routes/rma-android'
import { Route as QingDynastyMapRouteImport } from './routes/qing-dynasty-map'
import { Route as NightmodeRouteImport } from './routes/nightmode'
import { Route as GoogleMapsApiRouteImport } from './routes/google-maps-api'
import { Route as EvenMoreMapsRouteImport } from './routes/even-more-maps'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const ShadedReliefRoute = ShadedReliefRouteImport.update({
  id: '/shaded-relief',
  path: '/shaded-relief',
  getParentRoute: () => rootRouteImport,
} as any)
const RmaVisitorPostgisRoute = RmaVisitorPostgisRouteImport.update({
  id: '/rma-visitor-postgis',
  path: '/rma-visitor-postgis',
  getParentRoute: () => rootRouteImport,
} as any)
const RmaAndroidRoute = RmaAndroidRouteImport.update({
  id: '/rma-android',
  path: '/rma-android',
  getParentRoute: () => rootRouteImport,
} as any)
const QingDynastyMapRoute = QingDynastyMapRouteImport.update({
  id: '/qing-dynasty-map',
  path: '/qing-dynasty-map',
  getParentRoute: () => rootRouteImport,
} as any)
const NightmodeRoute = NightmodeRouteImport.update({
  id: '/nightmode',
  path: '/nightmode',
  getParentRoute: () => rootRouteImport,
} as any)
const GoogleMapsApiRoute = GoogleMapsApiRouteImport.update({
  id: '/google-maps-api',
  path: '/google-maps-api',
  getParentRoute: () => rootRouteImport,
} as any)
const EvenMoreMapsRoute = EvenMoreMapsRouteImport.update({
  id: '/even-more-maps',
  path: '/even-more-maps',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/even-more-maps': typeof EvenMoreMapsRoute
  '/google-maps-api': typeof GoogleMapsApiRoute
  '/nightmode': typeof NightmodeRoute
  '/qing-dynasty-map': typeof QingDynastyMapRoute
  '/rma-android': typeof RmaAndroidRoute
  '/rma-visitor-postgis': typeof RmaVisitorPostgisRoute
  '/shaded-relief': typeof ShadedReliefRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/even-more-maps': typeof EvenMoreMapsRoute
  '/google-maps-api': typeof GoogleMapsApiRoute
  '/nightmode': typeof NightmodeRoute
  '/qing-dynasty-map': typeof QingDynastyMapRoute
  '/rma-android': typeof RmaAndroidRoute
  '/rma-visitor-postgis': typeof RmaVisitorPostgisRoute
  '/shaded-relief': typeof ShadedReliefRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/even-more-maps': typeof EvenMoreMapsRoute
  '/google-maps-api': typeof GoogleMapsApiRoute
  '/nightmode': typeof NightmodeRoute
  '/qing-dynasty-map': typeof QingDynastyMapRoute
  '/rma-android': typeof RmaAndroidRoute
  '/rma-visitor-postgis': typeof RmaVisitorPostgisRoute
  '/shaded-relief': typeof ShadedReliefRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/even-more-maps'
    | '/google-maps-api'
    | '/nightmode'
    | '/qing-dynasty-map'
    | '/rma-android'
    | '/rma-visitor-postgis'
    | '/shaded-relief'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/even-more-maps'
    | '/google-maps-api'
    | '/nightmode'
    | '/qing-dynasty-map'
    | '/rma-android'
    | '/rma-visitor-postgis'
    | '/shaded-relief'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/even-more-maps'
    | '/google-maps-api'
    | '/nightmode'
    | '/qing-dynasty-map'
    | '/rma-android'
    | '/rma-visitor-postgis'
    | '/shaded-relief'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  EvenMoreMapsRoute: typeof EvenMoreMapsRoute
  GoogleMapsApiRoute: typeof GoogleMapsApiRoute
  NightmodeRoute: typeof NightmodeRoute
  QingDynastyMapRoute: typeof QingDynastyMapRoute
  RmaAndroidRoute: typeof RmaAndroidRoute
  RmaVisitorPostgisRoute: typeof RmaVisitorPostgisRoute
  ShadedReliefRoute: typeof ShadedReliefRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shaded-relief': {
      id: '/shaded-relief'
      path: '/shaded-relief'
      fullPath: '/shaded-relief'
      preLoaderRoute: typeof ShadedReliefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rma-visitor-postgis': {
      id: '/rma-visitor-postgis'
      path: '/rma-visitor-postgis'
      fullPath: '/rma-visitor-postgis'
      preLoaderRoute: typeof RmaVisitorPostgisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rma-android': {
      id: '/rma-android'
      path: '/rma-android'
      fullPath: '/rma-android'
      preLoaderRoute: typeof RmaAndroidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qing-dynasty-map': {
      id: '/qing-dynasty-map'
      path: '/qing-dynasty-map'
      fullPath: '/qing-dynasty-map'
      preLoaderRoute: typeof QingDynastyMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nightmode': {
      id: '/nightmode'
      path: '/nightmode'
      fullPath: '/nightmode'
      preLoaderRoute: typeof NightmodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/google-maps-api': {
      id: '/google-maps-api'
      path: '/google-maps-api'
      fullPath: '/google-maps-api'
      preLoaderRoute: typeof GoogleMapsApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/even-more-maps': {
      id: '/even-more-maps'
      path: '/even-more-maps'
      fullPath: '/even-more-maps'
      preLoaderRoute: typeof EvenMoreMapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  EvenMoreMapsRoute: EvenMoreMapsRoute,
  GoogleMapsApiRoute: GoogleMapsApiRoute,
  NightmodeRoute: NightmodeRoute,
  QingDynastyMapRoute: QingDynastyMapRoute,
  RmaAndroidRoute: RmaAndroidRoute,
  RmaVisitorPostgisRoute: RmaVisitorPostgisRoute,
  ShadedReliefRoute: ShadedReliefRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
